spring.application.name=comic-backend
# ===============================
# CẤU HÌNH SERVER SPRING BOOT
# ===============================
# Cổng chạy ứng dụng Backend (React sẽ gọi API vào cổng này)
server.port=${PORT:8080}

# ===============================
# CẤU HÌNH KẾT NỐI DATABASE MYSQL (DOCKER)
# ===============================
# Trỏ thẳng vào cổng 3307 và database comicWeb bạn vừa tạo
spring.datasource.url=${DB_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&serverTimezone=UTC}
# Điền username và password bạn đã thiết lập trong Docker
spring.datasource.username=${DB_USERNAME:3gdJcng6EpH2u5N.root}
spring.datasource.password=${DB_PASSWORD:cYIgqyARqnAtm94U}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CẤU HÌNH JPA & HIBERNATE
# ===============================
# QUAN TRỌNG: Để là "none" vì bạn đã tự chạy file SQL tạo bảng bằng tay rồi.
# Nếu để "update" hoặc "create", Spring Boot có thể sẽ làm loạn các khóa ngoại của bạn.
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL trong Console để dễ debug lúc code
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# CẤU HÌNH CLOUDINARY
# ===============================
cloudinary.cloud-name=comicWeb
cloudinary.api-key=164468354273354
cloudinary.api-secret=dgOzt0hTJDQZ9EFkzhGhi-lx3wg

# ===============================
# CẤU HÌNH TỐI ƯU CÂN BẰNG TẢI (PERFORMANCE TUNING)
# ===============================
# Tối ưu hoá JSON GZIP (Giảm 10 lần dung lượng băng thông)
server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/xml,text/plain,application/javascript,text/css
server.compression.min-response-size=1024

# Cấu hình Tomcat ThreadPool (Chịu tải 100-200 User truy cập cùng lúc)
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20
server.tomcat.accept-count=150

# Cấu hình bể kết nối HikariCP (Chống sập TiDB Free Plan)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000