spring.application.name=comic-backend
# ===============================
# CẤU HÌNH SERVER SPRING BOOT
# ===============================
# Cổng chạy ứng dụng Backend (React sẽ gọi API vào cổng này)
server.port=${PORT:8080}

# ===============================
# CẤU HÌNH KẾT NỐI DATABASE MYSQL (DOCKER)
# ===============================
# Trỏ thẳng vào cổng 3307 và database comicWeb bạn vừa tạo
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/comicWeb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
# Điền username và password bạn đã thiết lập trong Docker
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CẤU HÌNH JPA & HIBERNATE
# ===============================
# QUAN TRỌNG: Để là "none" vì bạn đã tự chạy file SQL tạo bảng bằng tay rồi.
# Nếu để "update" hoặc "create", Spring Boot có thể sẽ làm loạn các khóa ngoại của bạn.
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL trong Console để dễ debug lúc code
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# CẤU HÌNH CLOUDINARY
# ===============================
cloudinary.cloud-name=comicWeb
cloudinary.api-key=164468354273354
cloudinary.api-secret=dgOzt0hTJDQZ9EFkzhGhi-lx3wg